name: flutter_ui
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/loginScreen/login-screen-background.jpeg
    - assets/FlutterDayAndNightMoodAnimation/land_tree_light.png
    - assets/FlutterDayAndNightMoodAnimation/Sun.svg
